feat(notification): #CRRE-480 add notification for validator and precriber
CGI-OPEN-ENT-NG/entcore-css-lib pull request #32
Opened 2023-02-22 10:31 UTC by BastienBenard

2023-02-22 10:39 UTC, sjollois approved these changes

2023-02-22 10:52 UTC, JinDouang requested changes

2023-02-22 10:52 UTC, JinDouang commented on scss/specifics/crre/_crre.scss
> +@import "timeline/timeline";
Tu peux voir pour inclure l'import de timeline comme avec body.crre ?

Dans l'idée ça serait un truc du genre :  

```
  body.crre, .crre-notif {
   @import "timeline/timeline";
   ...
 }
```
Ta classe devrait être global genre "notif" pour que ton organisation concerne + les notifs.
Comme ça tu isoles le comportement css et en plus tu pourras potentiellement accéder aux autres classes css

2023-02-22 10:52 UTC, JinDouang commented on scss/specifics/crre/timeline/_timeline.scss
> +div.crre-timeline-new-notification {
Avec ta PR : https://github.com/CGI-OPEN-ENT-NG/crre/pull/51/files#diff-0f40e5561684b30a93e7279fce1381a8c519e07250b52f3bb9bdb582f00c2d9fR2

Tu pourrais avoir un truc du genre :  

```
<div class="crre-notif">
    <div class="crre-timeline-avatar">
        <img alt="CRRE" width="80" height="80" src="/crre/public/img/logo.png">
    </div>
    <div>
        {{#userId}}
        <a href="{{#host}}{{userId}}{{/host}}">{{username}}</a>
        <br>
        {{/userId}}
        <span>{{#i18n}}timeline.crre.new.notification{{/i18n}}</span>
        {{#message}}
        <br>
        <span>{{message}}</span>
        {{/message}}
    </div>
</div>
```

etc....

2023-02-22 14:21 UTC, qpic-cgi approved these changes

2023-02-23 09:35 UTC, BastienBenard commented
Vu avec Laurie, ce n'est plus d'actualiter. On ne veut pas de logo custom.

2023-02-23 09:35 UTC, closed without merging